name: jamset
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.6

  # Funzionalità principali
  csv: ^6.0.0
  file_picker: ^10.3.3
  http: ^1.2.1 # È meglio specificare una versione
  path: ^1.9.0 # La versione 1.9.1 è ok, 1.9.0 è comune
  path_provider: ^2.1.3
  permission_handler: ^11.3.1 # La versione 12 è in beta, meglio usare l'ultima stabile
  shared_preferences: ^2.2.3
  speech_to_text: ^7.3.0 # <-- VERSIONE NUOVA E COMPATIBILE
  # Database
  sqflite: ^2.3.3

  # Apertura file e URL
  #Sopener: ^10.1.1 # <-- NOME E VERSIONE CORRETTI
  url_launcher: ^6.3.0 # È meglio specificare una versione

  # Visualizzatore PDF integrato (per Android)
  flutter_pdfview: ^1.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
