name: jamset
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & UI
  cupertino_icons: ^1.0.6

  # Funzionalità principali
  csv: ^6.0.0
  file_picker: ^10.3.3
  http: any
  path: ^1.9.1
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: any

  # Apertura file e URL
  url_launcher: any

  # Visualizzatore PDF integrato (per Android)
  flutter_pdfview: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
